version: '3.3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8089:8089"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always
    
  redis:
    build:
      context: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    
  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "8080:8080"
